server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/stayhub_bd
    username: postgres
    password: abc123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect